"""Reference data shipped with Neo Dentiq: codes, procedures, drugs, kits, protocols."""

ITEM_GROUPS = [
	"Dental Services", "Dental Consumables", "Dental Materials", "Dental Implants",
	"Dental Instruments", "Dental Pharmacy", "Dental Lab Work",
]

ROLES = [
	("Neo Dentiq Manager", "Full practice, clinical and financial control."),
	("Dentist", "Clinical records, charting, prescribing, procedures."),
	("Dental Hygienist", "Hygiene, perio charting, preventive procedures."),
	("Front Desk", "Scheduling, patient registration, payments."),
	("Insurance Coordinator", "Eligibility, pre-auth, claims, remittance."),
	("Sterilization Officer", "Reprocessing cycles, traceability, infection control."),
	("Patient Portal User", "Patient self-service portal."),
]

SPECIALITIES = [
	("General Dentistry", "Primary dental care and routine restorative work."),
	("Endodontics", "Root canal therapy and treatment of dental pulp."),
	("Periodontics", "Gum disease, periodontal surgery and maintenance."),
	("Orthodontics", "Alignment, braces and clear aligner therapy."),
	("Oral & Maxillofacial Surgery", "Surgical extraction, trauma and jaw surgery."),
	("Prosthodontics", "Crowns, bridges, dentures and full-mouth rehabilitation."),
	("Paediatric Dentistry", "Dental care for children and adolescents."),
	("Oral Medicine & Pathology", "Mucosal disease and orofacial pain."),
	("Implantology", "Surgical and prosthetic implant dentistry."),
	("Dental Hygiene", "Preventive care, scaling and oral health education."),
	("Cosmetic Dentistry", "Whitening, veneers and smile design."),
	("Oral Radiology", "Dental imaging interpretation."),
]

# (name, parent, item group, default phase, colour)
CATEGORIES = [
	("Diagnostic", None, "Dental Services", "Phase 1 - Disease Control", "#64748b"),
	("Preventive", None, "Dental Services", "Phase 1 - Disease Control", "#22c55e"),
	("Restorative", None, "Dental Services", "Phase 2 - Definitive / Restorative", "#3b82f6"),
	("Endodontics", None, "Dental Services", "Phase 1 - Disease Control", "#f59e0b"),
	("Periodontics", None, "Dental Services", "Phase 1 - Disease Control", "#ec4899"),
	("Prosthodontics", None, "Dental Services", "Phase 3 - Rehabilitation", "#a855f7"),
	("Oral Surgery", None, "Dental Services", "Phase 0 - Emergency / Pain Relief", "#ef4444"),
	("Implantology", None, "Dental Services", "Phase 3 - Rehabilitation", "#14b8a6"),
	("Orthodontics", None, "Dental Services", "Phase 3 - Rehabilitation", "#8b5cf6"),
	("Paediatric Dentistry", None, "Dental Services", "Phase 2 - Definitive / Restorative", "#f97316"),
	("Cosmetic", None, "Dental Services", "Phase 3 - Rehabilitation", "#06b6d4"),
	("Adjunctive & Emergency", None, "Dental Services", "Phase 0 - Emergency / Pain Relief", "#dc2626"),
	("Radiology", "Diagnostic", "Dental Services", "Phase 1 - Disease Control", "#94a3b8"),
]

# (code, description, category)
CDT_CODES = [
	("D0120", "Periodic oral evaluation - established patient", "Diagnostic"),
	("D0140", "Limited oral evaluation - problem focused", "Diagnostic"),
	("D0150", "Comprehensive oral evaluation - new patient", "Diagnostic"),
	("D0180", "Comprehensive periodontal evaluation", "Periodontics"),
	("D0210", "Intraoral complete series of radiographic images", "Radiology"),
	("D0220", "Intraoral periapical first radiographic image", "Radiology"),
	("D0274", "Bitewings - four radiographic images", "Radiology"),
	("D0330", "Panoramic radiographic image", "Radiology"),
	("D0367", "Cone beam CT capture - both jaws", "Radiology"),
	("D0601", "Caries risk assessment - low risk", "Diagnostic"),
	("D0602", "Caries risk assessment - moderate risk", "Diagnostic"),
	("D0603", "Caries risk assessment - high risk", "Diagnostic"),
	("D1110", "Prophylaxis - adult", "Preventive"),
	("D1120", "Prophylaxis - child", "Preventive"),
	("D1206", "Topical application of fluoride varnish", "Preventive"),
	("D1351", "Sealant - per tooth", "Preventive"),
	("D1354", "Interim caries arresting medicament application", "Preventive"),
	("D2140", "Amalgam - one surface, primary or permanent", "Restorative"),
	("D2330", "Resin-based composite - one surface, anterior", "Restorative"),
	("D2331", "Resin-based composite - two surfaces, anterior", "Restorative"),
	("D2391", "Resin-based composite - one surface, posterior", "Restorative"),
	("D2392", "Resin-based composite - two surfaces, posterior", "Restorative"),
	("D2393", "Resin-based composite - three surfaces, posterior", "Restorative"),
	("D2740", "Crown - porcelain/ceramic", "Prosthodontics"),
	("D2750", "Crown - porcelain fused to high noble metal", "Prosthodontics"),
	("D2950", "Core buildup, including any pins", "Restorative"),
	("D2954", "Prefabricated post and core in addition to crown", "Restorative"),
	("D2960", "Labial veneer - resin, chairside", "Cosmetic"),
	("D2962", "Labial veneer - porcelain laminate", "Cosmetic"),
	("D3220", "Therapeutic pulpotomy", "Endodontics"),
	("D3310", "Endodontic therapy - anterior tooth", "Endodontics"),
	("D3320", "Endodontic therapy - premolar tooth", "Endodontics"),
	("D3330", "Endodontic therapy - molar tooth", "Endodontics"),
	("D3346", "Retreatment of previous root canal - anterior", "Endodontics"),
	("D3410", "Apicoectomy - anterior", "Endodontics"),
	("D4210", "Gingivectomy or gingivoplasty - per quadrant", "Periodontics"),
	("D4260", "Osseous surgery - four or more teeth per quadrant", "Periodontics"),
	("D4341", "Periodontal scaling and root planing - four or more teeth per quadrant", "Periodontics"),
	("D4342", "Periodontal scaling and root planing - one to three teeth per quadrant", "Periodontics"),
	("D4346", "Scaling in presence of generalised moderate gingival inflammation", "Periodontics"),
	("D4910", "Periodontal maintenance", "Periodontics"),
	("D5110", "Complete denture - maxillary", "Prosthodontics"),
	("D5120", "Complete denture - mandibular", "Prosthodontics"),
	("D5213", "Maxillary partial denture - cast metal with resin bases", "Prosthodontics"),
	("D6010", "Surgical placement of implant body - endosteal implant", "Implantology"),
	("D6057", "Custom fabricated abutment", "Implantology"),
	("D6058", "Abutment supported porcelain/ceramic crown", "Implantology"),
	("D6104", "Bone graft at time of implant placement", "Implantology"),
	("D6240", "Pontic - porcelain fused to high noble metal", "Prosthodontics"),
	("D7140", "Extraction, erupted tooth or exposed root", "Oral Surgery"),
	("D7210", "Surgical removal of erupted tooth requiring elevation of flap", "Oral Surgery"),
	("D7240", "Removal of impacted tooth - completely bony", "Oral Surgery"),
	("D7953", "Bone replacement graft for ridge preservation", "Oral Surgery"),
	("D8080", "Comprehensive orthodontic treatment - adolescent dentition", "Orthodontics"),
	("D8090", "Comprehensive orthodontic treatment - adult dentition", "Orthodontics"),
	("D8680", "Orthodontic retention - removal of appliances and placement of retainers", "Orthodontics"),
	("D9110", "Palliative treatment of dental pain - per visit", "Adjunctive & Emergency"),
	("D9222", "Deep sedation/general anaesthesia - first 15 minutes", "Adjunctive & Emergency"),
	("D9230", "Inhalation of nitrous oxide / anxiolysis", "Adjunctive & Emergency"),
	("D9944", "Occlusal guard - hard appliance, full arch", "Adjunctive & Emergency"),
	("D9972", "External bleaching - per arch, performed in office", "Cosmetic"),
	("D9995", "Teledentistry - synchronous, real-time encounter", "Adjunctive & Emergency"),
]

# (code, diagnosis, category)
ICD_CODES = [
	("K02.9", "Dental caries, unspecified", "Caries"),
	("K02.51", "Dental caries on pit and fissure surface penetrating into dentine", "Caries"),
	("K02.61", "Dental caries on smooth surface limited to enamel", "Caries"),
	("K03.0", "Excessive attrition of teeth", "Developmental"),
	("K03.1", "Abrasion of teeth", "Developmental"),
	("K03.2", "Erosion of teeth", "Developmental"),
	("K03.6", "Deposits (accretions) on teeth", "Periodontal"),
	("K04.0", "Pulpitis", "Pulpal / Periapical"),
	("K04.1", "Necrosis of pulp", "Pulpal / Periapical"),
	("K04.4", "Acute apical periodontitis of pulpal origin", "Pulpal / Periapical"),
	("K04.5", "Chronic apical periodontitis", "Pulpal / Periapical"),
	("K04.7", "Periapical abscess without sinus", "Pulpal / Periapical"),
	("K05.0", "Acute gingivitis", "Periodontal"),
	("K05.1", "Chronic gingivitis", "Periodontal"),
	("K05.30", "Chronic periodontitis, unspecified", "Periodontal"),
	("K05.4", "Periodontosis", "Periodontal"),
	("K06.0", "Gingival recession", "Periodontal"),
	("K01.1", "Impacted teeth", "Developmental"),
	("K07.30", "Crowding of fully erupted teeth", "Orthodontic"),
	("K07.60", "Temporomandibular joint disorder, unspecified", "TMJ / Orofacial Pain"),
	("K08.109", "Complete loss of teeth, unspecified cause", "Other"),
	("K12.0", "Recurrent oral aphthae", "Oral Mucosa"),
	("K12.30", "Oral mucositis (ulcerative), unspecified", "Oral Mucosa"),
	("K13.21", "Leukoplakia of oral mucosa, including tongue", "Oral Mucosa"),
	("M26.620", "Arthralgia of temporomandibular joint, unspecified side", "TMJ / Orofacial Pain"),
	("S02.5XXA", "Fracture of tooth (traumatic), initial encounter", "Trauma"),
	("Z01.20", "Encounter for dental examination and cleaning without abnormal findings", "Other"),
]

# (name, category, code, scope, duration, fee, flags...)
PROCEDURES = [
	("Comprehensive Oral Examination", "Diagnostic", "D0150", "Whole Mouth", 40, 250,
	 {"abbr": "COE"}),
	("Periodic Oral Examination", "Diagnostic", "D0120", "Whole Mouth", 20, 120, {}),
	("Emergency Pain Assessment", "Adjunctive & Emergency", "D9110", "Whole Mouth", 20, 150,
	 {"abbr": "EMG"}),
	("Periapical Radiograph", "Radiology", "D0220", "Per Tooth", 10, 50, {}),
	("Bitewing Radiographs (4)", "Radiology", "D0274", "Whole Mouth", 15, 120, {}),
	("Panoramic Radiograph (OPG)", "Radiology", "D0330", "Whole Mouth", 15, 200, {}),
	("CBCT Scan", "Radiology", "D0367", "Whole Mouth", 20, 600, {}),
	("Scaling and Polishing", "Preventive", "D1110", "Whole Mouth", 45, 300,
	 {"abbr": "PROPH", "kit": "Scaling & Perio Kit"}),
	("Fluoride Varnish Application", "Preventive", "D1206", "Whole Mouth", 15, 90, {}),
	("Fissure Sealant", "Preventive", "D1351", "Per Tooth", 20, 120, {"abbr": "SEAL"}),
	("Composite Restoration - One Surface", "Restorative", "D2391", "Per Surface", 40, 320,
	 {"abbr": "CO1", "kit": "Restorative Kit", "consent": 0}),
	("Composite Restoration - Two Surface", "Restorative", "D2392", "Per Surface", 50, 420,
	 {"abbr": "CO2", "kit": "Restorative Kit"}),
	("Composite Restoration - Three Surface", "Restorative", "D2393", "Per Surface", 60, 520,
	 {"abbr": "CO3", "kit": "Restorative Kit"}),
	("Amalgam Restoration - One Surface", "Restorative", "D2140", "Per Surface", 40, 280,
	 {"abbr": "AM1", "kit": "Restorative Kit"}),
	("Core Build-up", "Restorative", "D2950", "Per Tooth", 40, 400, {"kit": "Restorative Kit"}),
	("Root Canal Treatment - Anterior", "Endodontics", "D3310", "Per Tooth", 60, 900,
	 {"abbr": "RCT", "kit": "Endodontic Kit", "consent": 1, "radiograph": 1,
	  "pathway": "Root Canal Therapy - Single Visit", "warranty": 24}),
	("Root Canal Treatment - Premolar", "Endodontics", "D3320", "Per Tooth", 75, 1100,
	 {"abbr": "RCT", "kit": "Endodontic Kit", "consent": 1, "radiograph": 1, "warranty": 24}),
	("Root Canal Treatment - Molar", "Endodontics", "D3330", "Per Tooth", 100, 1500,
	 {"abbr": "RCT", "kit": "Endodontic Kit", "consent": 1, "radiograph": 1,
	  "visits": 2, "warranty": 24}),
	("Pulpotomy", "Paediatric Dentistry", "D3220", "Per Tooth", 40, 450,
	 {"kit": "Paedo Kit", "consent": 1}),
	("Scaling and Root Planing - Per Quadrant", "Periodontics", "D4341", "Per Quadrant",
	 45, 500, {"abbr": "SRP", "kit": "Scaling & Perio Kit", "consent": 1}),
	("Periodontal Maintenance", "Periodontics", "D4910", "Whole Mouth", 45, 380,
	 {"kit": "Scaling & Perio Kit"}),
	("Gingivectomy - Per Quadrant", "Periodontics", "D4210", "Per Quadrant", 45, 700,
	 {"kit": "Surgical Kit", "consent": 1, "surgical": 1}),
	("Porcelain Crown", "Prosthodontics", "D2740", "Per Tooth", 75, 2200,
	 {"abbr": "CR", "kit": "Prosthodontic Kit", "consent": 1, "lab": 1, "visits": 2,
	  "warranty": 60, "pathway": "Crown - Two Visit Protocol"}),
	("Porcelain Veneer", "Cosmetic", "D2962", "Per Tooth", 70, 2400,
	 {"abbr": "VEN", "kit": "Prosthodontic Kit", "consent": 1, "lab": 1, "warranty": 60}),
	("Bridge Pontic", "Prosthodontics", "D6240", "Per Tooth", 60, 2000,
	 {"kit": "Prosthodontic Kit", "lab": 1, "consent": 1}),
	("Complete Denture - Upper", "Prosthodontics", "D5110", "Per Arch", 60, 4500,
	 {"lab": 1, "consent": 1, "visits": 5}),
	("Cast Partial Denture", "Prosthodontics", "D5213", "Per Arch", 60, 3800,
	 {"lab": 1, "consent": 1, "visits": 4}),
	("Simple Extraction", "Oral Surgery", "D7140", "Per Tooth", 30, 350,
	 {"abbr": "EXT", "kit": "Extraction Kit", "consent": 1, "radiograph": 1,
	  "anaesthesia": 1, "surgical": 1}),
	("Surgical Extraction", "Oral Surgery", "D7210", "Per Tooth", 50, 750,
	 {"abbr": "SEXT", "kit": "Surgical Kit", "consent": 1, "radiograph": 1,
	  "anaesthesia": 1, "surgical": 1}),
	("Impacted Third Molar Removal", "Oral Surgery", "D7240", "Per Tooth", 75, 1600,
	 {"abbr": "IMP3", "kit": "Surgical Kit", "consent": 1, "radiograph": 1,
	  "anaesthesia": 1, "surgical": 1, "healing": 7}),
	("Ridge Preservation Graft", "Oral Surgery", "D7953", "Per Tooth", 45, 1800,
	 {"kit": "Surgical Kit", "consent": 1, "surgical": 1, "healing": 90}),
	("Implant Fixture Placement", "Implantology", "D6010", "Per Tooth", 90, 5500,
	 {"abbr": "IMPL", "kit": "Implant Surgical Kit", "consent": 1, "radiograph": 1,
	  "surgical": 1, "healing": 120, "warranty": 120,
	  "pathway": "Single Implant - Delayed Loading"}),
	("Implant Abutment", "Implantology", "D6057", "Per Tooth", 45, 1800,
	 {"kit": "Implant Surgical Kit", "lab": 1}),
	("Implant Supported Crown", "Implantology", "D6058", "Per Tooth", 60, 3200,
	 {"kit": "Prosthodontic Kit", "lab": 1, "warranty": 60}),
	("Comprehensive Orthodontics - Adult", "Orthodontics", "D8090", "Whole Mouth", 60, 18000,
	 {"consent": 1, "radiograph": 1, "visits": 24}),
	("Clear Aligner Therapy", "Orthodontics", "D8090", "Whole Mouth", 45, 22000,
	 {"consent": 1, "lab": 1, "visits": 14}),
	("Orthodontic Retainer", "Orthodontics", "D8680", "Per Arch", 30, 1200, {"lab": 1}),
	("In-Office Teeth Whitening", "Cosmetic", "D9972", "Per Arch", 60, 1500, {"consent": 1}),
	("Occlusal Night Guard", "Adjunctive & Emergency", "D9944", "Per Arch", 30, 1200,
	 {"lab": 1}),
	("Nitrous Oxide Sedation", "Adjunctive & Emergency", "D9230", "Whole Mouth", 30, 400,
	 {"consent": 1}),
	("Teledentistry Consultation", "Adjunctive & Emergency", "D9995", "Whole Mouth", 20, 150,
	 {}),
]

# (name, indication, [(step, procedure, description, gap_days, optional)])
PATHWAYS = [
	("Root Canal Therapy - Single Visit", "Irreversible pulpitis, vital tooth", [
		(1, "Periapical Radiograph", "Pre-operative diagnostic radiograph", 0, 0),
		(2, "Root Canal Treatment - Anterior", "Access, shaping, obturation", 0, 0),
		(3, "Core Build-up", "Definitive coronal seal", 0, 0),
		(4, "Porcelain Crown", "Cuspal coverage to prevent fracture", 14, 1),
	]),
	("Crown - Two Visit Protocol", "Structurally compromised tooth", [
		(1, "Periapical Radiograph", "Assess remaining tooth structure", 0, 0),
		(2, "Core Build-up", "Foundation restoration", 0, 1),
		(3, "Porcelain Crown", "Preparation, impression, temporisation", 0, 0),
		(4, "Porcelain Crown", "Try-in, cementation", 14, 0),
	]),
	("Single Implant - Delayed Loading", "Single missing tooth, adequate bone", [
		(1, "CBCT Scan", "3D planning and bone assessment", 0, 0),
		(2, "Implant Fixture Placement", "Surgical placement", 14, 0),
		(3, "Implant Abutment", "Second-stage abutment connection", 120, 0),
		(4, "Implant Supported Crown", "Definitive restoration", 21, 0),
	]),
	("Periodontal Therapy - Step 1 to 3", "Stage II-III periodontitis", [
		(1, "Comprehensive Oral Examination", "Full periodontal charting and diagnosis", 0, 0),
		(2, "Scaling and Polishing", "Supragingival debridement and oral hygiene phase", 0, 0),
		(3, "Scaling and Root Planing - Per Quadrant", "Subgingival instrumentation, quadrant 1-2", 14, 0),
		(4, "Scaling and Root Planing - Per Quadrant", "Subgingival instrumentation, quadrant 3-4", 7, 0),
		(5, "Periodontal Maintenance", "Re-evaluation at 3 months", 90, 0),
	]),
	("Impacted Third Molar Pathway", "Symptomatic impacted third molar", [
		(1, "Panoramic Radiograph (OPG)", "Assess root morphology and nerve proximity", 0, 0),
		(2, "CBCT Scan", "When the canal overlaps the roots", 0, 1),
		(3, "Impacted Third Molar Removal", "Surgical removal under local anaesthesia", 0, 0),
		(4, "Emergency Pain Assessment", "Post-operative review at one week", 7, 0),
	]),
]

# (kit name, sterilization class, cycle, [items])
INSTRUMENT_KITS = [
	("Examination Kit", "Semi-Critical", "Steam 134C Vacuum",
	 ["Mouth Mirror", "Dental Explorer", "Periodontal Probe", "College Tweezers"]),
	("Restorative Kit", "Semi-Critical", "Steam 134C Vacuum",
	 ["Mouth Mirror", "Amalgam Condenser", "Composite Instrument", "Matrix Band Retainer",
	  "Flat Plastic Instrument"]),
	("Endodontic Kit", "Critical", "Steam 134C Vacuum",
	 ["Endodontic Explorer", "Root Canal Spreader", "Endo Ruler", "Endodontic Plugger",
	  "Apex Locator Probe"]),
	("Extraction Kit", "Critical", "Steam 134C Vacuum",
	 ["Upper Universal Forceps", "Lower Universal Forceps", "Straight Elevator",
	  "Cryer Elevator", "Surgical Curette"]),
	("Surgical Kit", "Critical", "Steam 134C Vacuum",
	 ["Scalpel Handle", "Periosteal Elevator", "Rongeur", "Bone File", "Needle Holder",
	  "Suture Scissors", "Retractor"]),
	("Implant Surgical Kit", "Critical", "Steam 134C Vacuum",
	 ["Implant Drill Set", "Torque Wrench", "Depth Gauge", "Surgical Guide Holder",
	  "Bone Mill"]),
	("Scaling & Perio Kit", "Critical", "Steam 134C Vacuum",
	 ["Ultrasonic Scaler Tip", "Gracey Curette 1-2", "Gracey Curette 11-12",
	  "Gracey Curette 13-14", "Sickle Scaler"]),
	("Prosthodontic Kit", "Semi-Critical", "Steam 134C Vacuum",
	 ["Impression Tray Set", "Crown Remover", "Shade Guide Holder", "Articulating Paper Holder"]),
	("Paedo Kit", "Semi-Critical", "Steam 134C Vacuum",
	 ["Paediatric Mouth Mirror", "Paediatric Forceps", "Stainless Steel Crown Crimper"]),
	("Orthodontic Kit", "Semi-Critical", "Steam 134C Vacuum",
	 ["Bracket Placement Tweezers", "Distal End Cutter", "Ligature Director", "Band Pusher"]),
]

CONSUMABLES = [
	("Nitrile Gloves (Box)", "Dental Consumables", "Box"),
	("Face Mask Type IIR (Box)", "Dental Consumables", "Box"),
	("Disposable Bib", "Dental Consumables", "Nos"),
	("Saliva Ejector", "Dental Consumables", "Nos"),
	("Sterilization Pouch", "Dental Consumables", "Nos"),
	("Cotton Roll", "Dental Consumables", "Nos"),
	("Composite Resin A2", "Dental Materials", "Nos"),
	("Composite Resin A3", "Dental Materials", "Nos"),
	("Dental Amalgam Capsule", "Dental Materials", "Nos"),
	("Glass Ionomer Cement", "Dental Materials", "Nos"),
	("Bonding Agent", "Dental Materials", "Nos"),
	("Etchant Gel 37%", "Dental Materials", "Nos"),
	("Gutta Percha Points", "Dental Materials", "Nos"),
	("Endodontic Sealer", "Dental Materials", "Nos"),
	("Calcium Hydroxide Paste", "Dental Materials", "Nos"),
	("Impression Material - PVS", "Dental Materials", "Nos"),
	("Alginate Impression Powder", "Dental Materials", "Kg"),
	("Temporary Crown Material", "Dental Materials", "Nos"),
	("Suture 3-0 Silk", "Dental Consumables", "Nos"),
	("Bone Graft Granules 0.5g", "Dental Materials", "Nos"),
	("Collagen Membrane", "Dental Materials", "Nos"),
	("Titanium Implant Fixture 4.0x10mm", "Dental Implants", "Nos"),
	("Titanium Implant Fixture 4.3x11.5mm", "Dental Implants", "Nos"),
	("Healing Abutment 4.5mm", "Dental Implants", "Nos"),
	("Fluoride Varnish 5% NaF", "Dental Pharmacy", "Nos"),
	("Articaine 4% with Epinephrine", "Dental Pharmacy", "Nos"),
	("Lidocaine 2% with Epinephrine", "Dental Pharmacy", "Nos"),
]

# (name, generic, class, strength, dosage, frequency, days, route, flags)
MEDICATIONS = [
	("Amoxicillin 500mg", "Amoxicillin", "Penicillin Antibiotic", "500 mg", "1 capsule",
	 "Thrice a day", 5, "Oral", {"antibiotic": 1, "preg": "B"}),
	("Amoxicillin-Clavulanate 625mg", "Co-amoxiclav", "Penicillin Antibiotic", "625 mg",
	 "1 tablet", "Twice a day", 5, "Oral", {"antibiotic": 1, "preg": "B"}),
	("Metronidazole 400mg", "Metronidazole", "Nitroimidazole Antibiotic", "400 mg",
	 "1 tablet", "Thrice a day", 5, "Oral", {"antibiotic": 1, "preg": "B"}),
	("Clindamycin 300mg", "Clindamycin", "Lincosamide Antibiotic", "300 mg", "1 capsule",
	 "Four times a day", 5, "Oral", {"antibiotic": 1, "preg": "B"}),
	("Azithromycin 500mg", "Azithromycin", "Macrolide Antibiotic", "500 mg", "1 tablet",
	 "Once a day", 3, "Oral", {"antibiotic": 1, "preg": "B"}),
	("Erythromycin 500mg", "Erythromycin", "Macrolide Antibiotic", "500 mg", "1 tablet",
	 "Four times a day", 5, "Oral", {"antibiotic": 1, "preg": "B"}),
	("Cephalexin 500mg", "Cephalexin", "Cephalosporin Antibiotic", "500 mg", "1 capsule",
	 "Four times a day", 5, "Oral", {"antibiotic": 1, "preg": "B"}),
	("Ibuprofen 400mg", "Ibuprofen", "NSAID", "400 mg", "1 tablet", "Thrice a day", 3,
	 "Oral", {"preg": "C"}),
	("Naproxen 500mg", "Naproxen", "NSAID", "500 mg", "1 tablet", "Twice a day", 3,
	 "Oral", {"preg": "C"}),
	("Diclofenac 50mg", "Diclofenac", "NSAID", "50 mg", "1 tablet", "Thrice a day", 3,
	 "Oral", {"preg": "C"}),
	("Paracetamol 500mg", "Paracetamol", "Analgesic", "500 mg", "2 tablets",
	 "Four times a day", 3, "Oral", {"preg": "B"}),
	("Paracetamol-Codeine 500/30mg", "Co-codamol", "Opioid Analgesic", "500/30 mg",
	 "1 tablet", "Four times a day", 3, "Oral", {"controlled": 1, "preg": "C"}),
	("Chlorhexidine 0.12% Mouthwash", "Chlorhexidine gluconate", "Antiseptic", "0.12%",
	 "10 ml", "Twice a day", 7, "Rinse", {}),
	("Benzydamine Mouthwash", "Benzydamine", "Topical Analgesic", "0.15%", "15 ml",
	 "Thrice a day", 7, "Rinse", {}),
	("Nystatin Oral Suspension", "Nystatin", "Antifungal", "100000 units/ml", "1 ml",
	 "Four times a day", 7, "Oral", {"preg": "B"}),
	("Fluconazole 50mg", "Fluconazole", "Antifungal", "50 mg", "1 capsule", "Once a day",
	 7, "Oral", {"preg": "D"}),
	("Aciclovir 200mg", "Aciclovir", "Antiviral", "200 mg", "1 tablet", "Every 4 hours",
	 5, "Oral", {"preg": "B"}),
	("Triamcinolone Oral Paste 0.1%", "Triamcinolone acetonide", "Topical Corticosteroid",
	 "0.1%", "Thin film", "Thrice a day", 7, "Topical", {"preg": "C"}),
	("Tranexamic Acid 5% Mouthwash", "Tranexamic acid", "Antifibrinolytic", "5%", "10 ml",
	 "Four times a day", 5, "Rinse", {}),
	("Dexamethasone 4mg", "Dexamethasone", "Corticosteroid", "4 mg", "1 tablet",
	 "Once a day", 3, "Oral", {"preg": "C"}),
	("Articaine 4% with Epinephrine 1:100000", "Articaine", "Local Anaesthetic", "4%",
	 "1 carpule", "As needed", 1, "Submucosal", {}),
	("Lidocaine 2% with Epinephrine 1:100000", "Lidocaine", "Local Anaesthetic", "2%",
	 "1 carpule", "As needed", 1, "Submucosal", {}),
	("Mepivacaine 3% Plain", "Mepivacaine", "Local Anaesthetic", "3%", "1 carpule",
	 "As needed", 1, "Submucosal", {}),
	# Systemic medicines commonly on a patient's list — needed for interaction checking
	("Warfarin", "Warfarin sodium", "Anticoagulant", "5 mg", "1 tablet", "Once a day", 30,
	 "Oral", {"preg": "X"}),
	("Aspirin 75mg", "Acetylsalicylic acid", "Antiplatelet", "75 mg", "1 tablet",
	 "Once a day", 30, "Oral", {"preg": "D"}),
	("Clopidogrel 75mg", "Clopidogrel", "Antiplatelet", "75 mg", "1 tablet", "Once a day",
	 30, "Oral", {"preg": "B"}),
	("Alendronate 70mg", "Alendronic acid", "Bisphosphonate", "70 mg", "1 tablet",
	 "Once a day", 30, "Oral", {"preg": "C"}),
	("Methotrexate", "Methotrexate", "Antimetabolite", "10 mg", "1 tablet", "Once a day",
	 7, "Oral", {"preg": "X"}),
	("Simvastatin 40mg", "Simvastatin", "Statin", "40 mg", "1 tablet", "Once a day", 30,
	 "Oral", {"preg": "X"}),
	("Lithium Carbonate", "Lithium", "Mood Stabiliser", "400 mg", "1 tablet", "Twice a day",
	 30, "Oral", {"preg": "D"}),
	("Propranolol 40mg", "Propranolol", "Non-selective Beta Blocker", "40 mg", "1 tablet",
	 "Twice a day", 30, "Oral", {"preg": "C"}),
]

# (med A, med B, severity, effect, management)
INTERACTIONS = [
	("Metronidazole 400mg", "Warfarin", "Severe",
	 "Metronidazole inhibits warfarin metabolism, raising INR and bleeding risk.",
	 "Avoid if possible; otherwise monitor INR closely and consider clindamycin instead."),
	("Fluconazole 50mg", "Warfarin", "Severe",
	 "Azole antifungals markedly potentiate warfarin anticoagulation.",
	 "Use topical nystatin where possible; monitor INR."),
	("Ibuprofen 400mg", "Warfarin", "Severe",
	 "Additive bleeding risk plus gastric mucosal injury.",
	 "Use paracetamol for analgesia in anticoagulated patients."),
	("Naproxen 500mg", "Warfarin", "Severe",
	 "Additive bleeding risk with anticoagulation.", "Substitute paracetamol."),
	("Ibuprofen 400mg", "Methotrexate", "Severe",
	 "NSAIDs reduce renal methotrexate clearance, causing toxicity.",
	 "Avoid NSAIDs; use paracetamol."),
	("Erythromycin 500mg", "Simvastatin 40mg", "Contraindicated",
	 "CYP3A4 inhibition raises statin levels and risks rhabdomyolysis.",
	 "Choose amoxicillin or clindamycin instead of a macrolide."),
	("Azithromycin 500mg", "Warfarin", "Moderate",
	 "Macrolides may potentiate anticoagulant effect.", "Monitor INR."),
	("Ibuprofen 400mg", "Lithium Carbonate", "Moderate",
	 "NSAIDs reduce renal lithium clearance and raise serum lithium.",
	 "Avoid NSAIDs or monitor lithium levels."),
	("Ibuprofen 400mg", "Aspirin 75mg", "Moderate",
	 "Ibuprofen blocks the cardioprotective antiplatelet effect of aspirin.",
	 "Separate dosing or use paracetamol."),
	("Lidocaine 2% with Epinephrine 1:100000", "Propranolol 40mg", "Severe",
	 "Non-selective beta blockade with adrenaline can cause hypertensive crisis and "
	 "reflex bradycardia.",
	 "Limit to two carpules, aspirate carefully, or use a plain anaesthetic."),
	("Articaine 4% with Epinephrine 1:100000", "Propranolol 40mg", "Severe",
	 "Adrenaline-containing anaesthetic with non-selective beta blockade risks "
	 "hypertensive response.",
	 "Prefer mepivacaine 3% plain; monitor blood pressure."),
	("Amoxicillin 500mg", "Methotrexate", "Moderate",
	 "Penicillins reduce renal methotrexate excretion.", "Monitor for toxicity."),
	("Clindamycin 300mg", "Erythromycin 500mg", "Moderate",
	 "Competitive binding at the 50S ribosomal subunit antagonises both agents.",
	 "Do not co-prescribe."),
	("Paracetamol-Codeine 500/30mg", "Warfarin", "Moderate",
	 "Regular paracetamol can raise INR.", "Monitor INR with prolonged use."),
]

ALLERGIES = [
	("Penicillin", "Drug", "Rash, urticaria, anaphylaxis", 1),
	("Amoxicillin", "Drug", "Rash", 1),
	("Cephalosporins", "Drug", "Rash, cross-reactivity with penicillin", 1),
	("NSAIDs / Aspirin", "Drug", "Bronchospasm, angioedema", 1),
	("Sulfonamides", "Drug", "Rash, Stevens-Johnson syndrome", 1),
	("Local Anaesthetic (Amide)", "Anaesthetic", "Urticaria, hypotension", 1),
	("Latex", "Material", "Contact dermatitis, anaphylaxis", 1),
	("Nickel", "Material", "Contact stomatitis", 0),
	("Chlorhexidine", "Drug", "Mucosal irritation, anaphylaxis", 1),
	("Iodine / Povidone-Iodine", "Drug", "Contact dermatitis", 0),
	("Eugenol", "Material", "Contact mucositis", 0),
	("Dental Amalgam / Mercury", "Material", "Lichenoid reaction", 0),
	("Codeine / Opioids", "Drug", "Nausea, pruritus, respiratory depression", 1),
	("Peanuts", "Food", "Anaphylaxis", 1),
]

# (condition, icd, severity, prophylaxis, bleeding, anaesthesia, vasoconstrictor,
#  nsaids, clearance, implications, precautions)
MEDICAL_ALERTS = [
	("Hypertension", "I10", "Moderate", 0, 0, 1, 1, 1, 0,
	 "Stress and adrenaline can raise blood pressure intra-operatively.",
	 "Measure BP before treatment; limit adrenaline; short morning appointments."),
	("Type 2 Diabetes Mellitus", "E11.9", "High", 0, 0, 0, 0, 0, 0,
	 "Impaired healing, higher periodontitis and infection risk, xerostomia.",
	 "Morning appointments after a meal; check HbA1c; treat perio aggressively."),
	("Type 1 Diabetes Mellitus", "E10.9", "High", 0, 0, 0, 0, 0, 0,
	 "Hypoglycaemia risk during long appointments; impaired healing.",
	 "Keep glucose gel available; confirm the patient has eaten."),
	("Ischaemic Heart Disease", "I25.10", "High", 0, 0, 1, 1, 1, 1,
	 "Risk of angina or infarction under stress.",
	 "Limit adrenaline to two carpules; keep GTN spray to hand; defer elective care "
	 "within six months of infarction."),
	("Prosthetic Heart Valve", "Z95.2", "Critical", 1, 0, 0, 0, 0, 0,
	 "High risk of infective endocarditis from bacteraemia.",
	 "Antibiotic prophylaxis before any procedure involving gingival manipulation."),
	("Previous Infective Endocarditis", "I33.0", "Critical", 1, 0, 0, 0, 0, 0,
	 "Highest-risk category for recurrent endocarditis.",
	 "Antibiotic prophylaxis mandatory; liaise with cardiology."),
	("Rheumatic Heart Disease", "I09.9", "High", 1, 0, 0, 0, 0, 0,
	 "Valve damage raises endocarditis risk.", "Consider prophylaxis per local guidance."),
	("Anticoagulant Therapy", "Z79.01", "High", 0, 1, 0, 0, 1, 1,
	 "Prolonged bleeding after extraction or surgery.",
	 "Check INR within 24-72 hours; keep INR below 4.0; use local haemostatics and "
	 "tranexamic acid mouthwash."),
	("Antiplatelet Therapy", "Z79.02", "Moderate", 0, 1, 0, 0, 1, 0,
	 "Mildly prolonged bleeding.", "Do not stop therapy; use local measures."),
	("Haemophilia / Bleeding Disorder", "D66", "Critical", 0, 1, 0, 0, 1, 1,
	 "Severe post-operative haemorrhage.",
	 "Haematology clearance and factor cover before surgery; avoid blocks."),
	("Asthma", "J45.909", "Moderate", 0, 0, 0, 0, 1, 0,
	 "NSAIDs and sulphite preservatives can trigger bronchospasm.",
	 "Patient brings inhaler; avoid NSAIDs in aspirin-sensitive asthma."),
	("COPD", "J44.9", "Moderate", 0, 0, 0, 0, 0, 0,
	 "Poor tolerance of supine positioning and rubber dam.",
	 "Semi-upright chair position; avoid nitrous oxide in severe disease."),
	("Epilepsy", "G40.909", "High", 0, 0, 1, 0, 0, 0,
	 "Seizure risk; gingival overgrowth with phenytoin.",
	 "Minimise stress and flashing lights; secure airway; intensive plaque control."),
	("Stroke / CVA History", "I63.9", "High", 0, 1, 0, 1, 1, 0,
	 "Often anticoagulated; may have impaired oral clearance.",
	 "Short appointments; check anticoagulation; assist with hygiene."),
	("Chronic Kidney Disease", "N18.9", "High", 0, 1, 0, 0, 1, 1,
	 "Altered drug clearance, bleeding tendency, renal osteodystrophy.",
	 "Avoid NSAIDs; adjust antibiotic doses; treat the day after dialysis."),
	("Hepatitis B", "B18.1", "High", 0, 1, 0, 0, 1, 0,
	 "Impaired clotting factor synthesis; transmission risk.",
	 "Standard precautions; check LFTs and clotting; avoid hepatotoxic drugs."),
	("Hepatitis C", "B18.2", "High", 0, 1, 0, 0, 1, 0,
	 "Impaired haemostasis; transmission risk.", "Standard precautions; check clotting."),
	("HIV Infection", "B20", "High", 0, 0, 0, 0, 0, 0,
	 "Opportunistic oral infections; possible neutropenia.",
	 "Check CD4 and viral load; treat candidiasis; standard precautions."),
	("Immunosuppression / Chemotherapy", "D84.9", "Critical", 1, 1, 0, 0, 1, 1,
	 "Neutropenia, mucositis, severe infection risk.",
	 "Obtain blood counts; defer elective care during nadir; oncology clearance."),
	("Bisphosphonate Therapy", "Z79.83", "Critical", 0, 0, 0, 0, 0, 1,
	 "Risk of medication-related osteonecrosis of the jaw after extraction.",
	 "Avoid extraction and implants where possible; atraumatic technique; informed "
	 "consent for MRONJ risk."),
	("Head & Neck Radiotherapy", "Z92.3", "Critical", 0, 0, 0, 0, 0, 1,
	 "Osteoradionecrosis risk, xerostomia, radiation caries.",
	 "Pre-radiotherapy dental clearance; hyperbaric oxygen consideration; daily fluoride."),
	("Joint Replacement", "Z96.60", "Moderate", 0, 0, 0, 0, 0, 0,
	 "Historical prophylaxis concern; current guidance rarely requires it.",
	 "Prophylaxis only on the orthopaedic surgeon's advice."),
	("Cardiac Pacemaker / ICD", "Z95.0", "Moderate", 0, 0, 0, 0, 0, 0,
	 "Electromagnetic interference from some equipment.",
	 "Avoid magnetostrictive ultrasonic scalers and electrosurgery near the device."),
	("Pregnancy", "Z34.90", "High", 0, 0, 1, 0, 1, 0,
	 "Drug teratogenicity; supine hypotension; pregnancy gingivitis.",
	 "Treat in the second trimester; left lateral tilt; avoid NSAIDs and radiographs "
	 "where possible."),
	("Osteoporosis", "M81.0", "Moderate", 0, 0, 0, 0, 0, 0,
	 "Often on bisphosphonates or denosumab.", "Screen for antiresorptive therapy."),
	("Thyroid Disorder", "E03.9", "Moderate", 0, 0, 1, 1, 0, 0,
	 "Untreated hyperthyroidism is sensitive to adrenaline.",
	 "Confirm euthyroid status; limit vasoconstrictor."),
	("Gastro-oesophageal Reflux", "K21.9", "Low", 0, 0, 0, 0, 1, 0,
	 "Dental erosion on palatal surfaces.",
	 "Semi-upright position; fluoride and erosion counselling."),
	("Anxiety / Dental Phobia", "F40.8", "Moderate", 0, 0, 0, 0, 0, 0,
	 "Avoidance, late presentation, vasovagal episodes.",
	 "Consider nitrous oxide or oral sedation; longer, calmer appointments."),
	("Latex Sensitivity", "Z91.040", "High", 0, 0, 0, 0, 0, 0,
	 "Anaphylaxis risk from gloves and rubber dam.",
	 "Latex-free operatory; first appointment of the day."),
	("Sjogren Syndrome", "M35.00", "High", 0, 0, 0, 0, 0, 0,
	 "Severe xerostomia, rampant caries, candidiasis.",
	 "Saliva substitutes, high-fluoride paste, three-month recall."),
]

APPOINTMENT_TYPES = [
	("New Patient Examination", 60, "#2563eb", 1, 1, "Comprehensive Oral Examination", "General", 1),
	("Routine Check-up", 20, "#22c55e", 1, 0, "Periodic Oral Examination", "General", 0),
	("Hygiene / Scaling", 45, "#14b8a6", 1, 0, "Scaling and Polishing", "Hygiene", 0),
	("Emergency / Pain", 30, "#ef4444", 1, 1, "Emergency Pain Assessment", "General", 1),
	("Restorative Treatment", 60, "#3b82f6", 0, 0, None, "General", 0),
	("Root Canal Treatment", 90, "#f59e0b", 0, 0, None, "General", 0),
	("Extraction", 45, "#dc2626", 0, 0, "Simple Extraction", "Surgical", 0),
	("Implant Surgery", 120, "#0d9488", 0, 0, "Implant Fixture Placement", "Implantology", 0),
	("Crown / Bridge Prep", 75, "#a855f7", 0, 0, None, "General", 0),
	("Crown Fit", 30, "#a855f7", 0, 0, None, "General", 0),
	("Orthodontic Adjustment", 30, "#8b5cf6", 0, 0, None, "Ortho", 0),
	("Paediatric Visit", 30, "#f97316", 1, 1, None, "Pedo", 0),
	("Cosmetic Consultation", 45, "#06b6d4", 1, 1, None, "General", 0),
	("Teledentistry Consultation", 20, "#64748b", 1, 1, "Teledentistry Consultation", "Any", 0),
	("Post-operative Review", 15, "#94a3b8", 0, 0, None, "General", 0),
]

CANCELLATION_REASONS = [
	("Patient unwell", "Patient", 0, 0, 1),
	("Work commitment", "Patient", 0, 0, 1),
	("Transport problem", "Patient", 0, 0, 1),
	("Forgot appointment", "Patient", 1, 1, 1),
	("Did not attend without notice", "Patient", 1, 1, 1),
	("Cancelled under 24 hours", "Patient", 0, 1, 1),
	("Cost concern", "Patient", 0, 0, 1),
	("Insurance not approved", "Patient", 0, 0, 1),
	("Practitioner unavailable", "Practitioner", 0, 0, 0),
	("Clinic emergency", "Clinic", 0, 0, 0),
	("Equipment failure", "Clinic", 0, 0, 0),
	("Lab work not ready", "Clinic", 0, 0, 0),
	("Rescheduled by patient", "Patient", 0, 0, 1),
	("Duplicate booking", "System", 0, 0, 0),
]

RECALL_TYPES = [
	("Routine Check-up Recall", 6, "Periodic Oral Examination", 20, 12, 6, 3),
	("Hygiene Recall", 6, "Scaling and Polishing", 45, 12, 6, 3),
	("Periodontal Maintenance Recall", 3, "Periodontal Maintenance", 45, 6, 4, 3),
	("Paediatric Recall", 6, "Periodic Oral Examination", 30, 12, 6, 3),
	("Implant Review Recall", 12, "Periodic Oral Examination", 30, 12, 12, 6),
	("Orthodontic Retention Review", 6, None, 20, 12, 6, 6),
	("High Caries Risk Recall", 3, "Fluoride Varnish Application", 30, 6, 4, 3),
]

REFERRAL_SOURCES = [
	("Walk-in", "Walk-in"), ("Google Search", "Google / Search"),
	("Instagram", "Social Media"), ("Patient Referral", "Patient Referral"),
	("Referring Dentist", "Dentist Referral"), ("Physician Referral", "Physician Referral"),
	("Insurance Directory", "Insurance Directory"), ("Website Booking", "Google / Search"),
	("Local Campaign", "Campaign"), ("Corporate Contract", "Other"),
]

LAB_CASE_TYPES = [
	("Porcelain Crown", 7, 450, "Impression,Die Preparation,Coping Try-in,Glaze,Delivery"),
	("Zirconia Crown", 7, 600, "Impression,Design,Milling,Glaze,Delivery"),
	("Porcelain Veneer", 10, 500, "Impression,Wax-up,Try-in,Glaze,Delivery"),
	("Three-Unit Bridge", 10, 1200, "Impression,Framework Try-in,Bisque Try-in,Glaze,Delivery"),
	("Complete Denture", 21, 1400, "Primary Impression,Secondary Impression,Bite Registration,Tooth Try-in,Processing,Delivery"),
	("Cast Partial Denture", 21, 1100, "Impression,Framework Try-in,Tooth Try-in,Processing,Delivery"),
	("Night Guard", 7, 300, "Impression,Fabrication,Delivery"),
	("Clear Aligner Series", 21, 4000, "Scan,Treatment Plan Approval,Printing,Delivery"),
	("Orthodontic Retainer", 5, 250, "Impression,Fabrication,Delivery"),
	("Implant Custom Abutment", 10, 900, "Scan,Design,Milling,Delivery"),
	("Surgical Guide", 10, 1200, "CBCT Upload,Planning,Printing,Delivery"),
]

CONSENT_TEMPLATES = [
	("General Treatment Consent", None,
	 "I consent to the dental examination and treatment described to me by my clinician. "
	 "I confirm that I have disclosed a full and accurate medical history, including all "
	 "medications and allergies, and I understand I must report any change.",
	 "All dental treatment carries risk, including but not limited to discomfort, swelling, "
	 "bruising, infection, prolonged bleeding, allergic reaction to materials or medication, "
	 "and the possibility that the treatment does not achieve the intended outcome.",
	 "Alternatives discussed include no treatment, monitoring, or an alternative treatment "
	 "approach, together with the likely consequences of each option."),
	("Extraction Consent", "Oral Surgery",
	 "I consent to the removal of the tooth or teeth identified in my records, together with "
	 "any local anaesthesia required.",
	 "Risks include pain, swelling, bruising, bleeding, dry socket, infection, damage to "
	 "adjacent teeth or restorations, fractured root fragments, sinus communication for upper "
	 "teeth, temporary or permanent numbness of the lip, chin or tongue from nerve proximity, "
	 "and jaw stiffness.",
	 "Alternatives include root canal treatment, restoration, periodontal treatment, or leaving "
	 "the tooth in place with the risk of continued infection."),
	("Implant Surgery Consent", "Implantology",
	 "I consent to the surgical placement of one or more dental implants and any associated "
	 "bone grafting or membrane placement.",
	 "Risks include implant failure and the need for removal, infection, peri-implantitis, "
	 "bone or sinus complications, nerve injury causing temporary or permanent numbness, "
	 "graft rejection, aesthetic limitations, and the need for further surgery. Smoking, "
	 "uncontrolled diabetes and bisphosphonate therapy significantly increase failure risk.",
	 "Alternatives include a fixed bridge, a removable partial denture, or leaving the space "
	 "unrestored."),
	("Root Canal Treatment Consent", "Endodontics",
	 "I consent to root canal treatment on the tooth identified in my records.",
	 "Risks include instrument separation within the canal, perforation, incomplete cleaning "
	 "of complex canal anatomy, post-operative pain, persistent infection requiring surgery "
	 "or extraction, and fracture of the tooth if it is not subsequently crowned.",
	 "Alternatives include extraction with or without replacement, or monitoring without "
	 "treatment and accepting the risk of spreading infection."),
	("Orthodontic Treatment Consent", "Orthodontics",
	 "I consent to orthodontic treatment using the appliance system described to me.",
	 "Risks include root shortening, decalcification and decay around appliances, gum "
	 "inflammation, relapse if retainers are not worn as instructed, jaw joint symptoms, and "
	 "the possible need for extractions or surgery to achieve the planned result.",
	 "Alternatives include no treatment, limited treatment of the front teeth only, or "
	 "restorative camouflage."),
	("Sedation Consent", "Adjunctive & Emergency",
	 "I consent to conscious sedation as described to me and confirm I have followed the "
	 "pre-operative fasting and escort instructions.",
	 "Risks include nausea, drowsiness, headache, over-sedation requiring reversal, "
	 "respiratory depression, and paradoxical agitation.",
	 "Alternatives include local anaesthesia alone or behavioural management techniques."),
	("Teeth Whitening Consent", "Cosmetic",
	 "I consent to professional tooth whitening and understand that results vary between "
	 "individuals.",
	 "Risks include tooth sensitivity, gum irritation, uneven results, and the fact that "
	 "existing crowns, veneers and fillings will not change colour and may need replacement.",
	 "Alternatives include microabrasion, veneers, composite bonding, or no treatment."),
	("Photography & Records Consent", None,
	 "I consent to clinical photographs, radiographs and digital scans being taken and stored "
	 "as part of my dental record.",
	 "Images are stored securely. Any use for teaching or marketing requires my separate, "
	 "explicit and revocable permission.",
	 "I may decline photography without affecting my treatment."),
]

INTAKE_QUESTIONS = [
	("Reason for today's visit", "Small Text", None, 1, "None"),
	("Are you in pain right now?", "Check", None, 0, "None"),
	("On a scale of 0-10, how severe is the pain?", "Int", None, 0, "None"),
	("When did you last see a dentist?", "Data", None, 0, "None"),
	("Are you currently taking any medication?", "Small Text", None, 0, "Medication"),
	("Do you have any allergies?", "Small Text", None, 1, "Allergy"),
	("Do you have any of the following conditions?", "Small Text", None, 1, "Medical Alert"),
	("Have you ever had a serious reaction to local anaesthetic?", "Check", None, 0, "None"),
	("Do you take blood thinners?", "Check", None, 1, "Medical Alert"),
	("Have you ever taken bisphosphonates or bone-strengthening medication?", "Check",
	 None, 1, "Medical Alert"),
	("Do you smoke?", "Select", "Never\nFormer\nCurrent - Light\nCurrent - Heavy", 1,
	 "Smoking Status"),
	("Are you pregnant or breastfeeding?", "Check", None, 0, "Pregnancy"),
	("How often do you brush your teeth?", "Select", "Less than once a day\nOnce a day\nTwice a day\nMore", 0, "Caries Risk"),
	("Do you drink sugary or acidic drinks daily?", "Check", None, 0, "Caries Risk"),
	("Do you clench or grind your teeth?", "Check", None, 0, "None"),
	("Do your gums bleed when you brush?", "Check", None, 0, "None"),
	("Are you anxious about dental treatment?", "Select", "Not at all\nSlightly\nModerately\nVery\nExtremely", 0, "None"),
	("How did you hear about us?", "Data", None, 0, "None"),
]

RADIOGRAPH_TYPES = [
	("Periapical", "Intraoral Periapical", 0.005, 10),
	("Bitewing", "Bitewing", 0.005, 10),
	("Occlusal", "Occlusal", 0.008, 10),
	("Panoramic (OPG)", "Panoramic (OPG)", 0.015, 15),
	("Lateral Cephalogram", "Cephalometric", 0.006, 15),
	("CBCT - Small Field", "CBCT", 0.050, 20),
	("CBCT - Full Arch", "CBCT", 0.180, 25),
	("Intraoral Scan", "Intraoral Scan", 0.0, 20),
	("Clinical Photograph", "Photograph", 0.0, 10),
]

STERILIZER_DEFAULT = ("Autoclave 1", "Class B Vacuum Autoclave", 22.0, "Weekly")
